version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-net

  db:
    image: mysql:5.7
    container_name: food_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_order
      MYSQL_USER: food_user
      MYSQL_PASSWORD: food_pass
    ports:
      - "3306:3306"
    networks:
      - app-net

networks:
  app-net:
